/**
 * This file is part of Graylog PagerDuty plugin.
 *
 * Graylog PagerDuty Plugin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Graylog PagerDuty Plugin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Graylog PagerDuty Plugin.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.graylog.plugins.pagerduty;

import org.graylog2.plugin.PluginMetaData;
import org.graylog2.plugin.ServerStatus;
import org.graylog2.plugin.Version;

import java.net.URI;
import java.util.Collections;
import java.util.Set;

//Auto-generated by Graylog (graylog-project).

public class PagerDutyNotificationPluginMetaData implements PluginMetaData {
    private static final String PLUGIN_PROPERTIES =
        "org.graylog.plugins.graylog-plugin-pagerduty/graylog-plugin.properties";

    @Override
    public String getUniqueId() {
        return "org.graylog.plugins.pagerduty.PagerDutyNotificationPluginPlugin";
    }

    @Override
    public String getName() {
        return "PagerDutyNotificationPlugin";
    }

    @Override
    public String getAuthor() {
        return "Graylog Labs";
    }

    @Override
    public URI getURL() {
        return URI.create("https://github.com/graylog-labs/graylog-plugin-pagerduty");
    }

    @Override
    public Version getVersion() {
        return Version.fromPluginProperties(
            getClass(),
            PLUGIN_PROPERTIES,
            "version",
            Version.from(1, 0, 0, "unknown"));
    }

    @Override
    public String getDescription() {
        return "Plugin to send notifications to Pager Duty";
    }

    @Override
    public Version getRequiredVersion() {
        return Version.fromPluginProperties(
            getClass(),
            PLUGIN_PROPERTIES,
            "graylog.version",
            Version.from(3, 1, 0, "unknown"));
    }

    @Override
    public Set<ServerStatus.Capability> getRequiredCapabilities() {
        return Collections.emptySet();
    }
}
