/**
 * This file is part of Graylog PagerDuty plugin.
 *
 * Graylog PagerDuty Plugin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Graylog PagerDuty Plugin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Graylog PagerDuty Plugin.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.graylog.plugins.pagerduty;

import org.graylog2.plugin.PluginModule;

//Auto-generated by Graylog (graylog-project).

/**
 * Extend the PluginModule abstract class here to add you plugin to the system.
 */
public class PagerDutyNotificationPluginModule extends PluginModule {
    @Override
    protected void configure() {
        addNotificationType(
            PagerDutyNotificationConfig.TYPE_NAME,
            PagerDutyNotificationConfig.class,
            PagerDutyNotification.class,
            PagerDutyNotification.Factory.class);
    }
}
